# Generated by Django 5.2.16 on 2026-07-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoagenda',
            name='descricao_en',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='eventoagenda',
            name='descricao_pt',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='eventoagenda',
            name='local_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Local'),
        ),
        migrations.AddField(
            model_name='eventoagenda',
            name='local_pt',
            field=models.CharField(max_length=255, null=True, verbose_name='Local'),
        ),
        migrations.AddField(
            model_name='eventoagenda',
            name='titulo_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='eventoagenda',
            name='titulo_pt',
            field=models.CharField(max_length=255, null=True, verbose_name='Título'),
        ),
    ]
