# Generated by Django 5.2.16 on 2026-07-18 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_eventoagenda_descricao_en_eventoagenda_descricao_pt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventoagenda',
            name='descricao_en',
        ),
        migrations.RemoveField(
            model_name='eventoagenda',
            name='descricao_pt',
        ),
        migrations.RemoveField(
            model_name='eventoagenda',
            name='local_en',
        ),
        migrations.RemoveField(
            model_name='eventoagenda',
            name='local_pt',
        ),
        migrations.RemoveField(
            model_name='eventoagenda',
            name='titulo_en',
        ),
        migrations.RemoveField(
            model_name='eventoagenda',
            name='titulo_pt',
        ),
    ]
