# Generated by Django 5.2.15 on 2026-06-11 20:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('imagem', models.ImageField(help_text='Imagem da obra', upload_to='obras/', verbose_name='Imagem')),
                ('tecnica', models.CharField(max_length=100, verbose_name='Técnica')),
                ('dimensoes', models.CharField(blank=True, help_text='Ex: "130 × 105 cm"', max_length=80, verbose_name='Dimensões')),
                ('ano_criacao', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2027)], verbose_name='Ano de Criação')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível')),
                ('destaque', models.BooleanField(default=False, help_text='Marque para exibir na página inicial', verbose_name='Em destaque')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('serie', models.CharField(blank=True, max_length=120, verbose_name='Série / Colecção')),
                ('local_actual', models.CharField(blank=True, max_length=200, verbose_name='Localização actual')),
                ('exposicoes', models.TextField(blank=True, verbose_name='Exposições')),
                ('visivel', models.BooleanField(default=True, verbose_name='Visível no site')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ImagemObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='obras/extra/', verbose_name='Imagem')),
                ('legenda', models.CharField(blank=True, max_length=200)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_extra', to='obras.obra')),
            ],
            options={
                'verbose_name': 'Imagem adicional',
                'verbose_name_plural': 'Imagens adicionais',
                'ordering': ['ordem'],
            },
        ),
    ]
