# Generated by Django 5.2.16 on 2026-07-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemobra',
            name='legenda_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='imagemobra',
            name='legenda_pt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='descricao_en',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='obra',
            name='descricao_pt',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='obra',
            name='dimensoes_en',
            field=models.CharField(blank=True, help_text='Ex: "130 × 105 cm"', max_length=80, null=True, verbose_name='Dimensões'),
        ),
        migrations.AddField(
            model_name='obra',
            name='dimensoes_pt',
            field=models.CharField(blank=True, help_text='Ex: "130 × 105 cm"', max_length=80, null=True, verbose_name='Dimensões'),
        ),
        migrations.AddField(
            model_name='obra',
            name='exposicoes_en',
            field=models.TextField(blank=True, null=True, verbose_name='Exposições'),
        ),
        migrations.AddField(
            model_name='obra',
            name='exposicoes_pt',
            field=models.TextField(blank=True, null=True, verbose_name='Exposições'),
        ),
        migrations.AddField(
            model_name='obra',
            name='local_actual_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Localização actual'),
        ),
        migrations.AddField(
            model_name='obra',
            name='local_actual_pt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Localização actual'),
        ),
        migrations.AddField(
            model_name='obra',
            name='serie_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Série / Colecção'),
        ),
        migrations.AddField(
            model_name='obra',
            name='serie_pt',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Série / Colecção'),
        ),
        migrations.AddField(
            model_name='obra',
            name='tecnica_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Técnica'),
        ),
        migrations.AddField(
            model_name='obra',
            name='tecnica_pt',
            field=models.CharField(max_length=100, null=True, verbose_name='Técnica'),
        ),
        migrations.AddField(
            model_name='obra',
            name='titulo_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='obra',
            name='titulo_pt',
            field=models.CharField(max_length=200, null=True, verbose_name='Título'),
        ),
    ]
