# Generated by Django 5.2.16 on 2026-07-18 21:00

import portfolio_am_backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0002_imagemobra_legenda_en_imagemobra_legenda_pt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemobra',
            name='legenda_en',
        ),
        migrations.RemoveField(
            model_name='imagemobra',
            name='legenda_pt',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='descricao_en',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='descricao_pt',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='dimensoes_en',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='dimensoes_pt',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='exposicoes_en',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='exposicoes_pt',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='local_actual_en',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='local_actual_pt',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='serie_en',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='serie_pt',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='tecnica_en',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='tecnica_pt',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='titulo_en',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='titulo_pt',
        ),
        migrations.AlterField(
            model_name='imagemobra',
            name='imagem',
            field=models.ImageField(upload_to='obras/extra/', validators=[portfolio_am_backend.validators.ImageFileValidator()], verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='imagem',
            field=models.ImageField(help_text='Imagem da obra', upload_to='obras/', validators=[portfolio_am_backend.validators.ImageFileValidator()], verbose_name='Imagem'),
        ),
    ]
