# Generated by Django 5.2.15 on 2026-06-11 20:34

import django.db.models.deletion
import galeria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='Título do item da galeria', max_length=200, null=True, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, help_text='Descrição do item da galeria', verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, help_text='Imagem individual (use apenas se não referenciar uma obra)', null=True, upload_to=galeria.models.galeria_image_path, verbose_name='Imagem')),
                ('tipo', models.CharField(choices=[('evento', 'Evento'), ('exposicao', 'Exposição'), ('obra', 'Obra'), ('outros', 'Outros')], default='outros', help_text='Tipo do item da galeria', max_length=20, verbose_name='Tipo')),
                ('data', models.DateField(blank=True, help_text='Data relacionada ao item (evento, exposição, etc.)', null=True, verbose_name='Data')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, help_text='Se o item deve ser exibido na galeria', verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição (menor número aparece primeiro)', verbose_name='Ordem')),
                ('obra', models.ForeignKey(blank=True, help_text='Obra existente (use apenas se não carregar imagem individual)', null=True, on_delete=django.db.models.deletion.CASCADE, to='obras.obra', verbose_name='Obra Relacionada')),
            ],
            options={
                'verbose_name': 'Item da Galeria',
                'verbose_name_plural': 'Itens da Galeria',
                'ordering': ['ordem', '-data_criacao'],
            },
        ),
    ]
