# Generated by Django 5.2.16 on 2026-07-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemgaleria',
            name='slide_home',
            field=models.BooleanField(default=False, help_text='Marque para este item aparecer no carrossel/slide principal da página inicial', verbose_name='Exibir no slide da Home'),
        ),
    ]
