# Generated by Django 5.2.16 on 2026-07-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_itemgaleria_slide_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemgaleria',
            name='descricao_en',
            field=models.TextField(blank=True, help_text='Descrição do item da galeria', null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='itemgaleria',
            name='descricao_pt',
            field=models.TextField(blank=True, help_text='Descrição do item da galeria', null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='itemgaleria',
            name='titulo_en',
            field=models.CharField(blank=True, help_text='Título do item da galeria', max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='itemgaleria',
            name='titulo_pt',
            field=models.CharField(blank=True, help_text='Título do item da galeria', max_length=200, null=True, verbose_name='Título'),
        ),
    ]
