# Generated by Django 5.2.16 on 2026-07-18 21:00

import galeria.models
import portfolio_am_backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_itemgaleria_descricao_en_itemgaleria_descricao_pt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemgaleria',
            name='descricao_en',
        ),
        migrations.RemoveField(
            model_name='itemgaleria',
            name='descricao_pt',
        ),
        migrations.RemoveField(
            model_name='itemgaleria',
            name='slide_home',
        ),
        migrations.RemoveField(
            model_name='itemgaleria',
            name='titulo_en',
        ),
        migrations.RemoveField(
            model_name='itemgaleria',
            name='titulo_pt',
        ),
        migrations.AlterField(
            model_name='itemgaleria',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem individual (use apenas se não referenciar uma obra)', null=True, upload_to=galeria.models.galeria_image_path, validators=[portfolio_am_backend.validators.ImageFileValidator()], verbose_name='Imagem'),
        ),
    ]
