# Generated by Django 5.2.16 on 2026-07-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_remove_itemgaleria_descricao_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemgaleria',
            name='destaque',
            field=models.BooleanField(default=False, help_text='Marque para esta imagem aparecer no carrossel da página inicial. O item continua a aparecer normalmente em Exposições/Arquivo na Galeria.', verbose_name='Destaque (Carrossel da Home)'),
        ),
        migrations.AlterField(
            model_name='itemgaleria',
            name='tipo',
            field=models.CharField(choices=[('exposicao', 'Exposição'), ('arquivo', 'Arquivo')], default='arquivo', help_text='Tipo do item da galeria', max_length=20, verbose_name='Tipo'),
        ),
    ]
