# Generated by Django 5.2.16 on 2026-07-19 10:58

import galeria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_remove_itemgaleria_descricao_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemgaleria',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem individual (use apenas se não referenciar uma obra)', null=True, upload_to=galeria.models.galeria_image_path, verbose_name='Imagem'),
        ),
    ]
