# Generated by Django 5.2.16 on 2026-07-19 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_alter_itemgaleria_imagem'),
        ('galeria', '0006_remap_tipo_categorias'),
    ]

    operations = [
    ]
