# Generated by Django 5.2.16 on 2026-07-19 11:02

import galeria.models
import portfolio_am_backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0007_merge_20260719_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemgaleria',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem individual (use apenas se não referenciar uma obra)', null=True, upload_to=galeria.models.galeria_image_path, validators=[portfolio_am_backend.validators.ImageFileValidator()], verbose_name='Imagem'),
        ),
    ]
