# Generated by Django 5.2.15 on 2026-06-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Artista')),
                ('subtitulo', models.CharField(blank=True, help_text='Ex: "Artista Plástica & Escultural"', max_length=200, verbose_name='Subtítulo / Papel')),
                ('citacao', models.TextField(blank=True, help_text='Frase de manifesto exibida em itálico', verbose_name='Citação / Statement Artístico')),
                ('texto', models.TextField(help_text='Separe parágrafos com linha em branco (\\n\\n)', verbose_name='Texto Biográfico')),
                ('exposicoes', models.TextField(blank=True, help_text='Uma entrada por linha, formato: ano|local|título\nEx: 2026|Galeria Lisboa|O Peso da Luz', verbose_name='Exposições & Prémios')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='biografia/', verbose_name='Foto do Artista')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Biografia',
                'verbose_name_plural': 'Biografia',
            },
        ),
    ]
