# Generated by Django 5.2.16 on 2026-07-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biografia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biografia',
            name='citacao_en',
            field=models.TextField(blank=True, help_text='Frase de manifesto exibida em itálico', null=True, verbose_name='Citação / Statement Artístico'),
        ),
        migrations.AddField(
            model_name='biografia',
            name='citacao_pt',
            field=models.TextField(blank=True, help_text='Frase de manifesto exibida em itálico', null=True, verbose_name='Citação / Statement Artístico'),
        ),
        migrations.AddField(
            model_name='biografia',
            name='exposicoes_en',
            field=models.TextField(blank=True, help_text='Uma entrada por linha, formato: ano|local|título\nEx: 2026|Galeria Lisboa|O Peso da Luz', null=True, verbose_name='Exposições & Prémios'),
        ),
        migrations.AddField(
            model_name='biografia',
            name='exposicoes_pt',
            field=models.TextField(blank=True, help_text='Uma entrada por linha, formato: ano|local|título\nEx: 2026|Galeria Lisboa|O Peso da Luz', null=True, verbose_name='Exposições & Prémios'),
        ),
        migrations.AddField(
            model_name='biografia',
            name='subtitulo_en',
            field=models.CharField(blank=True, help_text='Ex: "Artista Plástica & Escultural"', max_length=200, null=True, verbose_name='Subtítulo / Papel'),
        ),
        migrations.AddField(
            model_name='biografia',
            name='subtitulo_pt',
            field=models.CharField(blank=True, help_text='Ex: "Artista Plástica & Escultural"', max_length=200, null=True, verbose_name='Subtítulo / Papel'),
        ),
        migrations.AddField(
            model_name='biografia',
            name='texto_en',
            field=models.TextField(help_text='Separe parágrafos com linha em branco (\\n\\n)', null=True, verbose_name='Texto Biográfico'),
        ),
        migrations.AddField(
            model_name='biografia',
            name='texto_pt',
            field=models.TextField(help_text='Separe parágrafos com linha em branco (\\n\\n)', null=True, verbose_name='Texto Biográfico'),
        ),
    ]
