# Generated by Django 5.2.16 on 2026-07-18 21:00

import portfolio_am_backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biografia', '0002_biografia_citacao_en_biografia_citacao_pt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biografia',
            name='citacao_en',
        ),
        migrations.RemoveField(
            model_name='biografia',
            name='citacao_pt',
        ),
        migrations.RemoveField(
            model_name='biografia',
            name='exposicoes_en',
        ),
        migrations.RemoveField(
            model_name='biografia',
            name='exposicoes_pt',
        ),
        migrations.RemoveField(
            model_name='biografia',
            name='subtitulo_en',
        ),
        migrations.RemoveField(
            model_name='biografia',
            name='subtitulo_pt',
        ),
        migrations.RemoveField(
            model_name='biografia',
            name='texto_en',
        ),
        migrations.RemoveField(
            model_name='biografia',
            name='texto_pt',
        ),
        migrations.AlterField(
            model_name='biografia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='biografia/', validators=[portfolio_am_backend.validators.ImageFileValidator()], verbose_name='Foto do Artista'),
        ),
    ]
