# Generated by Django 5.2.15 on 2026-06-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone_contacto', models.CharField(blank=True, max_length=20, verbose_name='Telefone de Contato')),
                ('email_contacto', models.EmailField(max_length=254, verbose_name='Email de Contacto')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('nome_facebook', models.CharField(blank=True, max_length=100, verbose_name='Nome no Facebook')),
                ('link_facebook', models.URLField(blank=True, verbose_name='Link do Facebook')),
                ('nome_instagram', models.CharField(blank=True, max_length=100, verbose_name='Nome no Instagram')),
                ('link_instagram', models.URLField(blank=True, verbose_name='Link do Instagram')),
                ('nome_x_twitter', models.CharField(blank=True, max_length=100, verbose_name='Nome no X (Twitter)')),
                ('link_x_twitter', models.URLField(blank=True, verbose_name='Link do X (Twitter)')),
                ('nome_whatsapp', models.CharField(blank=True, max_length=100, verbose_name='Nome no WhatsApp')),
                ('link_whatsapp', models.CharField(blank=True, max_length=20, verbose_name='Número WhatsApp')),
                ('enviar_email_automatico', models.BooleanField(default=True, verbose_name='Enviar Email Automático')),
                ('mensagem_agradecimento', models.TextField(default='Obrigado pelo seu contato! Responderemos em breve.', verbose_name='Mensagem de Agradecimento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Sistema Ativo')),
            ],
            options={
                'verbose_name': 'Configuração de Contato',
                'verbose_name_plural': 'Configurações de Contato',
            },
        ),
        migrations.CreateModel(
            name='MensagemContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(max_length=20)),
                ('assunto', models.CharField(max_length=200, verbose_name='Assunto')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('respondida', models.BooleanField(default=False, verbose_name='Respondida')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Mensagem de Contato',
                'verbose_name_plural': 'Mensagens de Contato',
                'ordering': ['-data_envio'],
            },
        ),
    ]
