# Generated by Django 5.2.16 on 2026-07-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaocontato',
            name='mensagem_agradecimento_en',
            field=models.TextField(default='Obrigado pelo seu contato! Responderemos em breve.', null=True, verbose_name='Mensagem de Agradecimento'),
        ),
        migrations.AddField(
            model_name='configuracaocontato',
            name='mensagem_agradecimento_pt',
            field=models.TextField(default='Obrigado pelo seu contato! Responderemos em breve.', null=True, verbose_name='Mensagem de Agradecimento'),
        ),
    ]
