# Generated by Django 5.2.16 on 2026-07-18 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0002_configuracaocontato_mensagem_agradecimento_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaocontato',
            name='mensagem_agradecimento_en',
        ),
        migrations.RemoveField(
            model_name='configuracaocontato',
            name='mensagem_agradecimento_pt',
        ),
    ]
